name: push
on:
  push:
    branches:
      - '*'
jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
        shell: bash
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: mc-ubuntu18
          dockerfile: 'docker-images/dind-az-helm/Dockerfile'
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
          registry: docker.io/moneycircles
          tag: ${{ env.GITHUB_REF_SLUG }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
